### ISSUE TITLE
Please tag versions & upload to rubygems

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [openzipkin/zipkin-tracer#11]
So we can bundle using `~> 0.4.0` for instance.

As of now only `0.2.0` is tagged. 
`0.2.1`, `0.3.1` & `0.4.0` are missing.

**Comment by jamescway** [comment]
@jfeltesse-mdsol I pushed the tags you request, and released them to rubygems.  v0.5.1 is the latest release.

**Comment by jfeltesse-mdsol** [comment]
:100:
