### ISSUE TITLE
use sucker_punch 2.0.0

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [openzipkin/zipkin-tracer#46]
This issue is just to track the progress of the various parties involved.

- sucker_punch 2.0.0 uses concurrent-ruby 1.0.0
- hermann depends on `~> 0.7.0` so can't bundle
 - asked for update of the gemspec, see https://github.com/reiseburo/hermann/issues/131

The cool thing with upgrading is we'd get rid of celluloid, which consumes a lot of memory.
~~The not so-cool thing is that ActionCable depends on celluloid so rails 5 users will end up with 2 concurrency libs~~ ActionCable head doesn't pull celluloid anymore! :tada:

**Comment by jcarres-mdsol** [comment]
Yes, concurrent-ruby is THE concurrent library! So yes, we should get out of celluloid asap

**Comment by jfeltesse-mdsol** [comment]
done in PR #59
