### ISSUE TITLE
Unable to POST spans to zipkin-server 1.1.4

### ISSUE THREAD

**Issue by singram** [openzipkin/zipkin-tracer#66]
Unable to post spans to zipkin-server using current zipkin trace version.

zipkin-tracer: 0.18.1
zipkin-server: 1.1.4

Zipkin server responds with a 400 code and message body
`"Cannot decode spans due to IllegalArgumentException(Expected a string but was NULL at path $[0].parentId reading List<Span> from json: [{\"name\":\"get\",\"traceId\":\"9c88dbcdd6a4c1e6\",\"id\":\"9c88dbcdd6a4c1e6\",\"parentId\":null,\"annotations\":[{\"value\":\"sr\",\"timestamp\":1465341141243210,\"endpoint\":{\"ipv4\":\"127.0.1.1\",\"port\":4567,\"serviceName\":\"quote-server\"}},{\"value\":\"ss\",\"timestamp\":1465341141247275,\"endpoint\":{\"ipv4\":\"127.0.1.1\",\"port\":4567,\"serviceName\":\"quote-server\"}}],\"binaryAnnotations\":[{\"key\":\"http.uri\",\"value\":\"/\",\"endpoint\":{\"ipv4\":\"127.0.1.1\",\"port\":4567,\"serviceName\":\"quote-server\"}}],\"timestamp\":1465341141243187,\"duration\":4095,\"debug\":false}])\n",`

Removing 'parentId' when nil resolved the issue for me in AsyncJsonApiClient class (zipkin_json_tracer.rb).  Will make a pull request when I have run through benchmarks/tests etc.

**Comment by adriancole** [comment]
I'll fix this
